import {
	type Context,
	Controller,
	createZIP,
	downloadBuffer,
	downloadFile,
	exportCSV,
	exportJSON,
	file,
	Get,
	Post,
	serveFileOrFallback,
	Use,
} from "@buntok/core";
import type { UploadedFile } from "@buntok/core/upload";
import { LocalDiskStorage, uploader } from "@buntok/core/upload";

const sampleRows = [
	{ id: 1, name: "Ada", role: "admin" },
	{ id: 2, name: "Linus", role: "user" },
	{ id: 3, name: "Grace", role: "user" },
];

@Controller("/files")
export class FilesController {
	@Get("/sample")
	sample() {
		return file("./public/sample.txt");
	}

	@Get("/fallback")
	fallback(ctx: Context) {
		return serveFileOrFallback(ctx, "./public/missing.txt", () =>
			ctx.json({ fallback: true, message: "File not found, fallback used" }, 404),
		);
	}

	@Get("/download")
	download(ctx: Context) {
		return downloadFile(ctx, "./public/sample.txt", "sample.txt");
	}

	@Get("/buffer")
	buffer(ctx: Context) {
		return downloadBuffer(
			ctx,
			new TextEncoder().encode("Generated bytes from downloadBuffer()\n"),
			"generated.txt",
		);
	}

	@Get("/export.csv")
	exportCsv(ctx: Context) {
		return exportCSV(ctx, sampleRows, "users.csv");
	}

	@Get("/export.json")
	exportJson(ctx: Context) {
		return exportJSON(ctx, sampleRows, "users.json");
	}

	@Get("/archive")
	archive(ctx: Context) {
		return createZIP(
			ctx,
			[
				{ name: "users.csv", data: "id,name,role\n1,Ada,admin\n2,Linus,user\n3,Grace,user" },
				{ name: "users.json", data: JSON.stringify(sampleRows, null, 2) },
			],
			"export.tar",
		);
	}
}

@Controller("/upload")
export class UploadController {
	@Post("/")
	@Use(
		uploader({
			storage: new LocalDiskStorage("./uploads"),
			fields: {
				avatar: {
					required: true,
					maxFileSize: 2 * 1024 * 1024,
					allowedMimeTypes: ["image/png", "image/jpeg", "image/webp"],
				},
			},
		}),
	)
	upload(ctx: Context) {
		const files = ctx.store.files as UploadedFile[];
		const fields = ctx.store.fields as Record<string, string | UploadedFile>;
		return {
			uploaded: files.map((f) => ({
				originalName: f.originalName,
				name: f.name,
				ext: f.ext,
				size: f.size,
				type: f.type,
				path: f.path,
			})),
			fields,
		};
	}
}
